import Head from 'next/head';
import Avatar from '../components/Avatar';
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"; // Import the FontAwesomeIcon component
import { faTh } from "@fortawesome/free-solid-svg-icons"; // import the icons you need
import { SearchIcon, MicrophoneIcon } from "@heroicons/react/solid";
import Image from "next/image/";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Doogle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex w-full p-5 justify-between text-gray-700">
        <div className="flex space-x-4 items-center">
        </div>
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          <FontAwesomeIcon icon={faTh} className="h-10 w-10 p-2 rounded hover:bg-gray-100 cursor-pointer"/>
          <Avatar url={'https://res.cloudinary.com/dineshscloud/image/upload/v1/blog/users/WhatsApp_Image_2021-04-05_at_12.06.05_AM_csz6xn_qnjvs9_xdgeij'} />
        </div>
      </header>
      <form className="flex flex-col items-center mt-44 flex-grow w-4/5">
        <Image 
        src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
        height={100}
        width={300}
        />
      <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl">
        <SearchIcon className="h-5 mr-3 text-gray-500 "/>
        <input type="text" className="flex-grow focus:outline-none" />
        <MicrophoneIcon className="h-5" />
      </div>
      <div className="flex flex-col w-1/2 space-y-2 justify-center sm:space-y-0 sm:flex-row sm:space-x-4">
        <button className="btn">Google Search</button>
        <button className="btn">I'm Feeling Happy</button>
      </div>
      </form>
    </div>
  )
}
