import Head from 'next/head';
import Header from "../components/Header";
import Body from  '../components/Body';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center md:h-screen lg:h-screen xl:h-screen 2xl:h-screen">
      <Head>
        <title>Doogle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Body />
      <Footer />
    </div>
  );
}

